"""
THIS FILE IS AUTO-GENERATED BY DJANGO.
Do not modify unless you have specific requirements.

WSGI config for voluntrack project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'voluntrack.settings')

application = get_wsgi_application()
