# Generated by Django 5.2.8 on 2025-11-27 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.department'),
        ),
    ]
