# Generated by Django 5.2.8 on 2025-11-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_make_event_department_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if applicable)'),
        ),
    ]
